# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-02 16:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=40)),
                ('temperature', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
