# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp_app', '0002_auto_20161102_2038'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tempchart',
            table='tempchart',
        ),
    ]
