# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp_app', '0003_auto_20161103_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempchart',
            name='date',
        ),
    ]
