# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp_app', '0004_remove_tempchart_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempchart',
            name='city_name',
        ),
    ]
